### ISSUE TITLE
Market Home Delivery Interaction

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/simcity201#11]
Since the market could be trying to scam us. How do we make sure this doesn't happen with a home delivery?

Can we transfer funds directly to the market's bank account and then have the bank will notify the market clerk that the payment was completed and notify the at home person that the transfer was completed? or Is this too unnatural?

If not, Could we pay for it with a credit card "over the phone", by messaging? or Could we get double charged and scammed? Would we have to call the bank to make sure the he didn't double charge us? or Could we just assume that the person checks his statement at the end of the month?

**Comment by dwilczyn** [comment]
I don't see how a home delivery is different from a restaurant delivery. There are 3 parts to any delivery:
1) The original order from the client.
2) The delivery to the client of the a) the goods, and b) the invoice
3) The client pays the invoice if all is ok. 
No scamming is possible with this natural method.

We're a cash-oriented city, which simplifies things as well.

**Comment by chadmart** [comment]
Well, that actually complicates things. What if the market delivery guy is busy with other orders and our person has to go to work?  Is the person going to wait until the delivery arrives? This seems unnatural. The person could have many responsibilities that he could no longer can meet due to this extended delivery time. How would we handle all of these secondary effects?

**Comment by dwilczyn** [comment]
Well, at first blush, I would ignore them, by having markets only deliver to open restaurants. PersonAgents must GO to the market. If there's time, we could try to handle home deliveries as a non-norm. I know home delivery is in the requirements, but requirements could change if they prove too complicated.
