### ISSUE TITLE
Individual Team Member Restaurants

### ISSUE THREAD

**Issue by marcuseng** [usc-csci201-fall2013/simcity201#12]
I was wondering how we should go about implementing our individual restaurants into the Sim City project. I believe this conflicts with the use of the Roles in our design as this would require five or six different versions of the restaurantCustomer,  restaurantWaiter, restaurantHost, restaurantCashier, and restaurantCook under Roles as each team members' restaurant agents are different (using different messages, passing different parameters, etc.).

Also, when a team members' restaurant needs to message the city's market for food, there may be five or six different versions of a message given to a market for the request, and this market would then need to handle the order appropriately and then have a correctly formatted message going back to the appropriate restaurant.

I understand that we need to do multiple restaurants, but I feel that there should be a single restaurant type that gets instantiated with different menus for serving different foods. This will save us from writing twenty-five to thirty different roles that are similar to each other but not enough to reuse in the different restaurants. It will also reduce complication when the restaurant needs to interact with a market (or even a bank when they need to withdraw/deposit money or take out a loan).

Thanks,
Marcus
@dwilczyn @crowley1958 @alghanmi

**Comment by chadmart** [comment]
2 issues have addressed this problem already. #1 #6

**Comment by marcuseng** [comment]
Okay, so then because the markets and bank that interact with the restaurant directly, these markets/banks must have 5-6 separate messages that do essentially the same thing?

**Comment by chadmart** [comment]
or you could make everyone change their design to match 1 protocol.

**Comment by dwilczyn** [comment]
Exactly, just agree on all the "external" messages.
