### ISSUE TITLE
Person - Bus Interaction

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/simcity201#13]
I am puzzled on how to get this interaction to happen. So the person goes to a bus stop and waits for the bus (goes to sleep). How does the agent get woken up  in order to get on the bus? Is this another producer-consumer situation where the bus stop is shared data? or should is there a way to make it not, like have the bus stop be an agent?

I was thinking the person goes to the bus stop, which is an agent, and messages the bus stop WaitingForBus(this). Then they get added to the list. When the bus gets to the stop it asks the bus stop for the list, gets the list, and messages all the people BusIsHere(this). The people message the bus ComingAboard(this, location). When the bus reaches a person stop, The bus will tell that person to getOffBus? Is this hack ok? or is there a more natural way of dong this?
@dwilczyn @crowley1958 @alghanmi

**Comment by dwilczyn** [comment]
I wouldn't mind having students discuss and design this, but, I think your solution is excellent and realistic. A person goes to a bus stop and pushes a button to register; the driverless bus gets the wireless messages and knows to stop there. The person gets on the bus and maybe registers with the bus (all with messages, of course). I wouldn't call that a hack at all.

**Comment by chadmart** [comment]
Thank you. That helps a lot. I was really unsure of myself. I am going to leave this open for a bit, so it doesn't get lost in closed issues and gets re-asked again.

**Comment by dwilczyn** [comment]
You're welcome. And still, there's much more to this problem, as is typical of concurrent simulations. I'd want you to consider very carefully the interaction of the animation counterparts to the agents and role players. I wouldn't mind seeing a sophisticated solution. Maybe we'll talk about this particular one in class this week.

**Comment by clay-to-n** [comment]
Could we do away with the BusStopAgent and only have a BusAgent?  The person would get to the bus stop, and message the bus that he's at a certain stop number.  When the bus gets there, it messages him back, and the person gets on the bus.  

Is this first message (potentially across the city) to the bus allowed?

**Comment by richy0101** [comment]
I like clay-to-n's idea because it is more straightforward. I feel like the BusStopAgent is a little unnecessary if the personagent could just send a message to the bus WaitingForBus(this,location) and the bus just adds the customer and location to a custom waitingPeople list (it could be like a futuristic text message system...). Then the busAgent could just circle through the list and see which person's location is closest to the current bus' location and when arriving the bus arrives at that location, sends a message to all waitingPeople who's location is that bus stop's location to get on the bus. (basically bus stops would just be graphics, but would not be agents at all, just used as location markers, kind of like tables in the restaurant)

Would this work @dwilczyn?

**Comment by dwilczyn** [comment]
There are many buses on the same route.  How would you know which to message? The point of a busStopAgent is to record the presence of a person, and get that information to an oncoming bus. This is the interesting animation problem I was alluding to.

rich0101's solution is a good start, but has many un-noted complications. For example, his WaitingForBus(this,location) message would have to be broadcast to ALL buses. The buses themselves would have to coordinate which one will service each request. It's doable for sure. Try it. I think the BusStopAgent is easier.

**Comment by chadmart** [comment]
We were planning on having 1 bus because a bus on bus accident will cause major problem with our design. Do we need more than 1 or are you okay with just 1 bus? The bus should be able to complete his route in about 30 seconds so 2 buses seem unnecessary. @dwilczyn

**Comment by dwilczyn** [comment]
I guess I'd prefer more buses. Hard to imagine how "a bus on bus accident will cause major problem with our design." Is your design so fragile than a bus accident could derail it -- sorry for the mixed metaphor, impossible to resist.

Also, I envisioned buses LEAVING the screen image of SimCity201 on one street and reentering later at another position. But, it's your design.

**Comment by chadmart** [comment]
I guess it would just cause a lot of deaths which could slow down everything. All of the people would be reincarnated in their homes and would have to go wait for a new bus in order to get to work. This would cause a rush hour. People may be late. Others might have to stay at work longer.

We were planning on having 1 bus snake through the city. If a bus and car get into an accident, then the bus would still be able to continue its route and the people in the car would die.

**Comment by dwilczyn** [comment]
What happened to walking fast?
