### ISSUE TITLE
Cash-oriented City?

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/simcity201#14]
"We're a cash-oriented city, which simplifies things as well."

Our team was thinking about having a direct deposit protocol for paying rent and employees. The Banking system will notify both parties if the transaction is complete, but only notify the sender if the money doesn't go through.

That way the non-payment scenarios could be non-norms that are easily handled later and the person paying would not have to find/walk to the person to give the money too. 

Is that ok? or Do you want us to make it a cash-oriented city?
@dwilczyn @crowley1958 @alghanmi

**Comment by dwilczyn** [comment]
I'm ok with that proposal.
