### ISSUE TITLE
Business Bank Accounts

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/simcity201#15]
Since people can't be trusted, how do we deposit money in the business's bank accounts? Can we trust our employees to do it? At the end of the day could the cashier or market clerk go to the bank and just deposit money in the account? Or will this too be subject to scams? Should a manager have to verify everything? This seems complicated.

@dwilczyn @crowley1958 @alghanmi

**Comment by dwilczyn** [comment]
My dilemma with the simple Market/Cashier protocol that I criticized in the restaurant was not only was it was so easy to scam, but, more importantly, unrealistic. Such bad design.

As chadmart points out there are points of trust in every system in the real world and scammers can find a way. What to do? Understand your trust points. When you hire an employee to deposit money, you have a high degree of trust there. If he scams you, that's a non-norm. Are we going to worry about every non-norm? No. I want us to find a few interesting ones.

And should you verify that your bank deposits actually happened. I do. Should your agents/roles? Up to you. This kind of work should be secondary to getting the system up.
