### ISSUE TITLE
bank customer role 

### ISSUE THREAD

**Issue by gabelew** [usc-csci201-fall2013/simcity201#16]
Every time the person goes into the bank they might have a different purpose (depositing, withdrawing, getting a loan). Should the person agent be initiating a different bankcustomerrole each time with different parameters so the bank customer role scheduler knows what to do when the role becomes active?

**Comment by chadmart** [comment]
@dwilczyn @crowley1958 @alghanmi

**Comment by dwilczyn** [comment]
I would think one role would have all those capabilities. Our waiter is a model for this. He can seat customers, take their orders, get their food, etc.

**Comment by gabelew** [comment]
Yes, but in the restaurant the customer always starts the scheduler by ImHungry. In a market the customer will always start trying to buy what's in their shopping list. But in the bank there is no set message that should always start first. How would the Person know what they want to do in the bank once they've taken on the BankCustomerRole? And what if the customer went to the bank to both withdraw from a personal account and deposit into a business account? Those actions don't necessarily go in sequence.

Would it be acceptable to have the PersonAgent message the BankCustomerRole with their "purpose", put it onto a list of tasks inside the BankCustomerRole and then complete that list of tasks once they take on that BankCustomerRole?

When a transaction such as a withdrawal completes, I assume the bank should message the BankCustomerRole? If they message the BankCustomerRole with the money, then how does the BankCustomerRole "transfer" the money back to the PersonAgent's cashOnHand? Should it be another message back to the PersonAgent? I am not fully understanding the switching back and forth from the various Roles to the PersonAgent.

**Comment by dwilczyn** [comment]
It's not a matter of STARTING the scenario, it's as you point out knowing what you want to do. And the personAgent knows what he wants to do; that's how the role gets started. Since any roles are completely within the auspices of the PersonAgent, you can simply set variables from the PersonAgent within the role, or if you prefer, send a message as you suggested.
