### ISSUE TITLE
Putting it all together

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/simcity201#18]
You have been saying just start with something simple, but its hard to put it all together. I don't quite understand what the person should be doing, what the roles should be doing, and how the 2 work together to make stuff happen. This project is not simple at all. I know I am not the only one with this opinion. I think we need more time and more help in order to complete this assignment. 

@dwilczyn @crowley1958 @alghanmi

**Comment by dwilczyn** [comment]
OK. You already have 5 restaurants. I'm going to try to design a simple system with many persons and one restaurant:
1) Create a SimCity window. Put in a simple panel person's are created. For right now just hardcode 5 PersonAgents: 4 for the CookRole, HostRole, WaiterRole, and CashierRole and one for the CustomerRole.
2) Make a simple Person Agent, with one map of restaurants (with the address and host pointer), one gotHungry message, one rule and one action go to a restaurant in the map. When you build the restaurantCustomer role it should include all the necessary information, probably only the hostRole pointer. I would think the person "goes" to restaurant, once "in" the restaurant takes on the restaurantCustomerRole. And then some simple behavior for "leaving" the restaurant and taking back his Person behavior.
2) Insert one of your restaurants into your new restaurants package: the restaurantPanel into the animation, and the renamed agents. Your CustomerRole will start with action that sends the WantFood(restaurantCustomerRole  rcr) message.
3) Hardcode in a couple of persons in the person panel and hardcode in the particular restaurant you chose.

So, ONE new agent--the personAgent with the new role behavior-- and one restaurant. Get the person in and out of the restaurant. Your SimCityWindow is new, the restaurant mostly the same (without customer creation) but the restaurant animation is the SAME. You could even leave the Waiters, Cook and Host in there as agents in the first go around. Remember the Customer/Person only sees them through their interface type.

Isn't that doable by the team in ONE 5 hour meeting? Let me know.

**Comment by chadmart** [comment]
I wasn't talking about implementation. I think we need more time to do the design. Tuesday is too soon. We don't understand how to design the personAgent and how the personAgent should interact with the roles. This is very complicated and confusing. My group is lost, and we would appreciate another weekend. I know the semester is coming to an end, but a good design will make implementation a lot easier.

**Comment by dwilczyn** [comment]
You need to get going with your preliminary implementation. I doubt that you as a team are capable of a fully functional design without some implementation experience. I always say that more design is usually the answer to most problems, but in a case like this, with so many new ideas floating around, you need some implementation to GROUND your preliminary design ideas.

So, you'll have your design reviewed in lab this week, and, of course, I'll be talking about your ideas with you in class this week.

**Comment by chadmart** [comment]
I don't think we understand the preliminary design ideas. We are lost.

**Comment by dwilczyn** [comment]
Hard to understand. Lost where?

I haven't heard this complaint from any other team.

**Comment by chadmart** [comment]
How do roles become active? How do roles become inactive? How does the person decide what role to do first? How does the person know what to do while in that i.e. bank scenarios?  ...and so on... There are many roles. Sometimes 2 roles will be active at the same time like when you must pay rent at work. We are really confused on how to do this and prevent clobbering.

Also, what communication should be between the role and the person? What should the person know about the roles? What should the roles know about the person?

Furthermore, this project feels like it is setting us up for failure. It is not entirely your fault. We did not have cs200, which might have helped. Although, I am not sure the CPs could do this either. They had a more feasible straight forward project. This whole role-agent communication seems beyond the scope of this class, but maybe we just don't understand it like you do. I feel we have not had the proper instruction to complete this project. We spent 2 months on the restaurant and you babied us through it, which I thought was unnecessary. It was simple and straight forward what should happen. This is much more complex, and we only have 4 weeks without any instruction on how to build the interactions. This is why we are lost.

**Comment by gabelew** [comment]
Are we going to need 5 different Restaurant classes since each will have different CustomerRole, CookRole etc?

**Comment by dwilczyn** [comment]
I believe all the questions asked by chadmart and gabelew were answered in my original document and in other posts about agents/roles. Please reread that document and review the posts. I will review the entire concept in the next class.
