### ISSUE TITLE
Stolen Cars?

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/simcity201#19]
Do cars need to know who there owner is? Or can we assume that cars will not be stolen and people who own cars can and will only interact with their own car?
@dwilczyn @crowley1958 @alghanmi

**Comment by dwilczyn** [comment]
I guess I wouldn't worry about that for now. My car doesn't know me. Anyone with my keys can get in and drive away. Not long from now cars will indeed have a dna or other physical id key. But, there will always be stolen cars and ids.

 Maybe in later non-norms?
