### ISSUE TITLE
General Principles

### ISSUE THREAD

**Issue by dwilczyn** [usc-csci201-fall2013/simcity201#2]
Before I start commenting on questions and issues, I want to make it clear what some of my motivations are for the SimCity201 project:
1) As many of you have already discovered, doing SimCity201 from my requirements doc is more than just design. You have to make in-the-large ARCHITECTURAL decisions, i.e., organizational details. This is good. Large system design is about just this kind of thing. My Person-With-Roles design fell into this category and it's hard.
2) The business about reading in configuration files to populate different SimCity201 scenarios is a standard technique for you to acquire. You can't populate SimCity201  by using GUI screens alone--it would minutes to get a full run going. Learning to design a configuration file, reading it in, parsing it, etc. is a great skill to have. Java has many classes for just this purpose. CAN I GET A CP TO POST AN EXAMPLE??
3) Code like SimCity201 has many organizational components: how do we integrate 5 restaurants, how does a PersonAgent know about all the services offered by SimCity201 , etc. We actually solved these problems in-the-small with our restaurants. You have to learn how to TRANSFER those skills to other larger problems.
4) ... and so on.

I want you to flex your computer science muscles in this project, and, of course, your team skills.

Prof. Wilczynski

**Comment by eerie444** [comment]
> 2) The business about reading in configuration files to populate different SimCity201 scenarios is a standard technique for you to acquire. You can't populate SimCity201 by using GUI screens alone--it would minutes to get a full run going. Learning to design a configuration file, reading it in, parsing it, etc. is a great skill to have. Java has many classes for just this purpose. CAN I GET A CP TO POST AN EXAMPLE??

Are configuration files still a requirement? If so, is there an example we can use?

**Comment by dwilczyn** [comment]
It's going to happen very soon. Rami has the code, he only has to post it.

**Comment by alghanmi** [comment]
An illustrated discussion of how to use properties files in java is now available on the [course website](http://www-scf.usc.edu/~csci201/resources.html):

> http://www-scf.usc.edu/~csci201/java/properties.html

This was wiritten and developed by @dmaulik
