### ISSUE TITLE
Unreasonable due dates

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/simcity201#27]
The normative scenarios's are far more complex than anticipated. My team has good design now, but we haven't slept in a week. In order to get v1 done in a week, we would have to drop all of our other responsibilities, not sleep, and maybe hire people to help code it. Given the fact that we have other classes, jobs, interviews, and cannot hire help, we need an extension. This project is very interesting. I wish we had more time to complete it, but we only have a few weeks left in the semester. I suggest you cancel v2 and move v1 back 2 weeks. Please take some time to carefully consider my request.

@dwilczyn @crowley1958 @alghanmi @mahdiazmandian

**Comment by dwilczyn** [comment]
I will discuss this with Crowley in a few minutes.

**Comment by chadmart** [comment]
Thank You.

**Comment by dwilczyn** [comment]
Here's our tentative proposal to redoing the dates:
1) Preliminary design still due this week. (Mostly to check your progress)
2) v1 and final design due Tuesday, Nov.26 (Day before Thanksgiving Holiday)
3) v2 due Mon. Dec. 9.
4) NO FINAL
5) Presentations by team: Wed Dec 11 4:30-??, Thurs, Dec 12 2pm-4pm,  Friday Dec 13 11-1 (if necessary). We are hoping to get most teams done on Wednesday.

**Comment by alghanmi** [comment]
The updated deadlines are listed in the [Assignments](http://www-scf.usc.edu/~csci201/assignments.html) page and  in the Deliverables section of the [team project](http://www-scf.usc.edu/~csci201/team/) page
