### ISSUE TITLE
Bank Teller Agents

### ISSUE THREAD

**Issue by jdgreenberger** [usc-csci201-fall2013/simcity201#31]
Should there be more than one bank? Should a bank have more than teller agent?

**Comment by dwilczyn** [comment]
Your design.

**Comment by dwilczyn** [comment]
Let me amend that comment about it being your design. It's your decision to only design ONE bank and create ONE instance in your SimCity201. However:
1) DO NOT build that fact into your PersonAgent.
2) You still have to make sure that every person on your project is doing about the SAME amount of work.  One of the ramifications of the the new schedule--No Final exam--is that graders are going to look MUCH more closely into the individual contribution. Much more about this later.

**Comment by wontonst** [comment]
I am glad we found a resolution to this 5+ year old issue.

**Comment by dwilczyn** [comment]
Do you boys want a grade increase? Ha. What's everybody doing nowadays. I was golfing when I got these notices.

Prof. Wilczynski (retired)

**Comment by BachDinh1994** [comment]
Everyone will have (hopefully) graduated by now :) 
How have you been Prof. Wilczynski? I was golfing a bit around Florida, but up here in Washington it's a just a bit more chilly.

**Comment by eamonb123** [comment]
I went to the Top Golf driving range in Vegas if that counts
