### ISSUE TITLE
Eclipse Error when running restaurant in Team repository

### ISSUE THREAD

**Issue by jasonhof** [usc-csci201-fall2013/simcity201#34]
We've been searching for the source of this error for about an hour now, so we decided to make an issue.

We imported a completely functional v2.2 restaurant into a branch of our Team repository in Eclipse.  We then refactored the import packages to match up with the correct packages in our Team repository.  Now, when we run the RestaurantGui code as we did in our restaurant, the error that comes out is as follows:

"Error: Could not find or load main class jason_restaurant.gui.RestaurantGui"

We're not sure how to fix this, but we'd like to get the restaurant running before we try to integrate a Person class in this restaurant.  Some of the subjects that popped up on StackOverflow are jar files and Buildpaths.  We've tried a couple things and still get the same error.

Thanks!

**Comment by tginick** [comment]
Next to the play button, there's an downward arrow. Click that, click run configurations. Select the restaurant configuration and click the 2nd button at the top to duplicate it. Then change the main class to whatever your main class is in sim city.

You might have to change the project name too.

**Comment by jasonhof** [comment]
Thanks man! That worked.
