### ISSUE TITLE
Grading SimCity201 and overall grading issues

### ISSUE THREAD

**Issue by dwilczyn** [usc-csci201-fall2013/simcity201#35]
The change in schedule and removal of the final means that Prof. Crowley and I have to come up with a new grading algorithm from the one in the syllabus. Our ideas are in this post. You can comment on them as you wish. We will read and consider anything you say. After all, it was a student comment that we agreed with whole-heartedly that caused this change in the first place. Here goes:
1)  The weights of all the previously graded assignments will be raised, enough to probably represent about half of your grade.
2)  We will look into your SimCity201 project much more deeply to inspect individual contribution. How will we do that?
• Peer reviews will be analyzed. One probably next week (Nov. 18 or 19). I would definitely come to class that day.
• Not only will we look at individual’s code, but we will look carefully at its unit testing.
• We will look not so much at how many lines of code you wrote, but whether your contribution is broad: everyone is required to do agent/role coding, animation coding, and GUI control coding.
• Your individual restaurants will be looked at again and graded carefully to see if the new producer-consumer additions are correct, that interfaces and signatures were changed appropriately, etc.
• Your individual score will be 75%, team score 25%.
• IF YOUR INDIVIDUAL SCORE IS POOR, SAY LESS THAN 70%, THEN YOU WILL GET A ZERO TEAM SCORE.
3)  We will do the above for v1 and v2.

**Comment by diegovb** [comment]
I disagree a little with this part: "everyone is required to do agent/role coding, animation coding, and GUI control coding."

When we started the project, we were encouraged to divide the labor based on our individual strengths. My team, at least, proceeded that way and since we have 6 people, not everyone was assigned a building (besides our own restaurants) to work the agent design and implementation. Would updating our individual restaurants for the new requirements be enough to satisfy the "broadness" requirement, or do we need to involve more than one person in the development of each of the buildings?

**Comment by lshiffer** [comment]
I agree with Diegovb.

My team is six people as well and our current division of labor has two people working exclusively on the Gui and animation with the rest working on Agents, Roles, and support objects.

We anticipate some overlap amongst the areas of labor but there is no guarantee the Gui people will ever work on anything else other than their own Restaurants, and the same for some of us working on the rest ever touching the Gui.  Especially for the v1.

Later versions, once everything is laid out and we all have a working knowledge of the structure we all put in place, it is more likely we will crossover into other areas of labor (Such as adding a new feature that requires tweaks to the Gui), but for this beginning state we really prefer to have our components as isolated as possible and constructed by as few people as possible.

**Comment by dwilczyn** [comment]
I disagree. I may not have said this to every class, but I believe and told some classes just the opposite. Each team member should work to his/her weakness. If you are inexperienced at gui, you should work on the gui, if you are weak on agents, work on agents. I am not a product manager at a company, in which case I would share your strategy. I am a professor and want each of you to develop ALL the necessary skills.

Might this strategy impact your grade negatively? So what.

**Comment by diegovb** [comment]
Fair enough, but it would still be complicated to distribute a bit of everything to everyone, considering what I wrote above (more people than buildings, someone has to deal with GUI or animation). If we assign someone to deal with GUI, they will most probably deal with that and not with agent design. Would that be a problem?

**Comment by johngtimms** [comment]
@kkthxby3 raises a good point, which is that it makes sense for there to be a very clear division of labor in version one. Complex systems being written from scratch require architecture decisions to be made, and while they may be made as a group it will make sense for one or two people to be responsible for the initial implementation. I understand that the desire is for everyone to make multidisciplinary contributions, but perhaps that requirement should be focused more on version two than version one.

Am I understanding the proposed re-weighting correctly?

5% Active Learning
45% Labs and Restaurant
50% SimCity (75% individual, 25% team)

How does the midterm fit in? Will our previous Restaurant submissions be re-graded at all?

Finally, please consider how rearranging grades will affect current student's grades. Students look at their current position across all of their classes when deciding where to focus their studying efforts. It would not be fair for major modifications to weights (the day before the drop deadline and 3 weeks before finals) propel some students ahead and put others behind.

**Comment by lshiffer** [comment]
The work broken up into components does not imply that everyone is working to their strengths.  Several members of my team chose their portion of the work because they wanted the challenge of working with something they are less experienced with.  Such as the Gui.  

At this stage in development, my team is focused on getting the foundation of the program set up.  As Johngtimms mentioned, there are many architectural decisions that need to be made for every component.  While my team has a unified, external set-up (The overall flow and how everything communicates) the internal workings are being worked out as they are developed.  It is far too cumbersome to have multiple people be apart of that initial development process, especially when everyone wants at least one part of the program to be theirs.

We also want to avoid anyone overrunning someone else's internal design, especially when that design might be unfinished and therefore not ready for changes from someone else.  Additionally, we want everyone to be fully accountable for their initial portion of the work.  If something doesn't work properly when we have our first run, the original designer can be called to address their code.  However, if everyone has been in there messing around, it makes it more difficult to troubleshoot and to determine who is responsible.

Once this foundation is complete, however, it will be much easier for everyone to dabble across all components of the program.  At that point everyone on the team will be aware of the final architecture of each individual component and can easily make changes as needed (Such as adding a new feature to a Role that requires a new animation or creating a Hack for a Role that they can now add to the Gui).

**Comment by dwilczyn** [comment]
We will resolve the grading issues before the end of the week. Our proposal is sound and may need a LITTLE tweaking, but not much. I know people who did well on the first midterm will want it more weighted, etc. That's obvious. Mostly, you will have to trust your professors. Any decision we make here will make SOMEONE unhappy.

One student came to me and proposed that he was responsible for the gui, someone else for the blah, blah, blah, etc. I discouraged that. What I suggested was that since he was expert on gui, others should do THAT work, and he should take responsibility for mentoring them. I FEEL STRONGLY THAT THIS IS THE CORRECT APPROACH.

The argument saying that V1 is a preliminary implementation and people should do what they do best, and that for V2 everyone can participate using V1 as a template is a GOOD ONE. However, I have heard that argument before and it doesn't work out that way. V2 is just more of the same; everyone stays in the specialized roles.

Please, please consider the mentoring model I have proposed.

**Comment by dwilczyn** [comment]
I didn't see kkthxby3 last comment before I put my post up. kkthxby3  makes many excellent points. As I said, history with this project denies her conclusion that "Once this foundation is complete, however, it will be much easier for everyone to dabble across all components of the program." Any way we can get guarantees of this behavior?

**Comment by meldefon** [comment]
Why not make just it a grading requirement for v2 and not v1? We'll all divide the work and get a working version - v1 - and then for v2 we are graded on the breadth of our contribution.

**Comment by johngtimms** [comment]
I agree with @meldefon. That's also what I was suggesting.

**Comment by khupka** [comment]
In terms of "examination points" and "project points", what about making the "individual points" worth what the final would be? In this respect, it separates the issue of mixing individual and group grades for exam points.  What I mean by this is and based on the syllabus:

75% of course grade = original grading scheme
25% of course grade = individual project grade

This would then increase team contribution as well.

As for the making it a requirement of "breadth of work", I feel that students are approaching this project as, how can we make this the best it can be?  This means putting the best people on the tasks they are best suited for.  This is a large scale project and progress will be slowed down if we take the learning approach considering our time constraints, the difficultly of the project, and unforeseen requirements that will be added closer to the deadline (this has been the trend with the Restaurant project).  My recommendation would to be scale back the project if you want to focus on learning or let us do what we do best if you want to maintain the scope of the current project.  The majority of students are overwhelmed and stressed about this project already and considering this is not our only class, including this "breadth requirement" would not help the matter.

**Comment by crowley1958** [comment]
I like khupka's suggestion that the individual score on the team project counts for an exam. It could be 50 individual points on V1 and 50 individual points on V2. The total would be 100 points - the equivalent points for the final exam.

The team points for V1 and V2 would count for the original project points.

**Comment by dwilczyn** [comment]
OK. Let's see how that plays out in total. The original scores from syllabus were:
5%  In class active learning work and Blackboard active learning tests
25% Labs and Restaurant deliveries
20% Midterm Exam
25% Team project deliveries
25% Final Exam

So, if we make the individual scores for v1 and v2 worth the 25% of the total, and the team score worth the 25% as in the syllabus, the grading scheme would look like this:

5%  In class active learning work and Blackboard active learning tests
25% Labs and Restaurant deliveries
20% Midterm Exam
12.5%  Team project v1 score (everyone on team gets this score except those whose individual score < 70%)
12.5%  Individual v1 score
12.5%  Team project v2 score (everyone on team gets this score except those whose individual score < 70%)
12.5%  Individual v2 score

So, all the original percentages for the work/exam done earlier in the semester are the same. This works for me.

**Comment by dwilczyn** [comment]
Let me address the breadth problem as well. Probably at this point in the semester khupka is right. Your team has some energy and direction and it probably shouldn't be changed. However, and I cannot stress this enough, with the new grading scheme, the work you do as an individual will be graded with MUCH MORE CARE. Say your contribution is just a BankTellerRole, but you do it perfectly. That will NOT get you maximum points. 

Crowley and I will put together a rubric of points for the project soon. Its contents will surely not surprise you.  We'll define all the parts of the project as we see it and assign each part points. Say the sum is 200 points, then if your team is 5 members, each should do 40 points of the work. Right?

Larger teams will have to do more, I'll propose the extra work in a post this weekend.

**Comment by ztanner** [comment]
How will extra credit work for the team grading? One of our group members is using databases for the Bank. Does that mean the team will get the extra credit, or just the person doing it?

Also, for people who are strictly focusing on GUI, how are we graded for unit testing? I imagine we aren't expected to unit test a GUI.

**Comment by dwilczyn** [comment]
Only the person doing the work will get extra credit. 

People working only on the GUI will DEFINITELY have to unit test it, using the same techniques even though it isn't agent code.

**Comment by xurex** [comment]
My team finds the alterations to the grading policy regarding large groups to be unfair. Although we fully agree that a larger group is capable of solving a larger problem, we do not think that a larger group necessitates a stricter grading policy.

As a larger group, we still have our individual restaurants to code. Additionally, we must deal with added coordination costs and must divide our project into smaller tasks, thus increasing implementation difficulty. Assigning a simple problem to a large group and requiring everyone to contribute is actually quite a complex problem.

Furthermore, by removing our opportunities for extra credit, we are disadvantaged. As a group, the best we can possibly achieve is full marks while other members in smaller groups are eligible for extra credit. For example, even if we were to have extraordinary animations as opposed to "better" animations, we can currently only receive base credit.

We do support the added requirement of parties, but disagree with the change to our grading standards. We ask that you please reconsider the grading amendments for larger groups.

Thanks,
Team 28

@dwilczyn @crowley1958

**Comment by alghanmi** [comment]
To conclude this thread, the updated grading weights are now in the Grading section of the [course syllabus](http://www-scf.usc.edu/~csci201/syllabus.html)
