### ISSUE TITLE
CP Help

### ISSUE THREAD

**Issue by jasonhof** [usc-csci201-fall2013/simcity201#38]
Team 13 was planning to meet this afternoon at 2 PM in SAL to get help from the CP office hours.  However, we just learned that CP office hours are cancelled this week.  Is there any way one of the CPs could meet us in SAL to help in some Git Hub and workspace issues?

Thank You

**Comment by alghanmi** [comment]
The CP office hour change was announced to the class via email which also mentioned that CPs can be available during their scheduled office hour by prior appointment.

Your team mentor should be the first person you contact when assistance is needed.

Finally, for team specific issues, please use the team issue tracker. You can @ mention specific teaching staff members if you wish. All GitHub account are listed on the course [contacts page](http://www-scf.usc.edu/~csci201/contacts.html).
