### ISSUE TITLE
Passing superclass Role when a subclass is expected

### ISSUE THREAD

**Issue by jdgreenberger** [usc-csci201-fall2013/simcity201#39]
I'm getting an error in my scheduler when I try to pass in a Role into a building scenario. Here is the situation:

a restaurantCustomerRole is waitingToExecute and ready to begin the restaurant scenario. 

scheduler:

for (Role r: roles)
   if (r.state == waitingToExecute && instanceof restaurantCustomerRole)
         restaurantHost.msgImHungry(r);

The method "msgImHungry" only accepts the role of type restaurantCustomerRole. I'm getting the error when I try to pass in r in the method "msgImHungry". Apparently, even though I know that r is an instance of restaurantCustomerRole, msgImHungry only sees the object as its superclass "Role".

What is the solution to this issue? Casting Role as the subclass restaurantCustomerRole?

**Comment by diegovb** [comment]
You can only implicit-cast a class into it's superclasses or interfaces, not the other way around. So yeah, you need explicit casting.

**Comment by dwilczyn** [comment]
You have to do the cast as diegovb, but I think the msgImHungry message should take a Customer and not restaurantCustomerRole as its argument. That way you'll be ready for MockCustomer as well.

**Comment by jdgreenberger** [comment]
Great, thank you!
