### ISSUE TITLE
Rolls changing data in person

### ISSUE THREAD

**Issue by dacaraway** [usc-csci201-fall2013/simcity201#45]
When a person's roll is about to end, say in the market, the person needs to get some data : ie how much he paid / what he bought at the market.  Is the marketCustomerRoll allowed to change this data in the person?  Or does the roll need to send this info in a message?  I am not sure if it is considered shared data even though they are running the same thread so the are the "same person"?

@dwilczyn

**Comment by Valakor** [comment]
It was my assumption that since a Person "is" that Role in a sense, shared data is allowed. It would be much more cumbersome to force roles to message the Person to change things like money, etc.

**Comment by pixelprizm** [comment]
Yeah, shared data between a PersonAgent and its roles should be okay because the roles don't run in separate threads.

**Comment by dwilczyn** [comment]
Yes, I agree. The person and the role are one and the same.
