### ISSUE TITLE
v1 and Suicidal Thoughts

### ISSUE THREAD

**Issue by dwilczyn** [usc-csci201-fall2013/simcity201#52]
The point of v1 is to ensure that you're making GOOD progress on the project in preparation for v2. In the past that meant having a good handle on the normative scenarios and leaving the non-norms for v2. v1 is not supposed to drive you to suicide. No fatalities is my number one goal.

That said, I understand all the rationalizations for your feeling behind. We've tried to accommodate them by changing dates and removing the final. Even so, you are still feeling stressed.

To relieve some of it, let me suggest some reductions in scope that still will result in a compliant v1. Of course, everything has to be in v2, it's just v1 I'm talking about. You get to pick one of the following 2 options--NOT both of them.
1. No City View. That means no animation for roads, pedestrians, etc. The agents/roles have to be complete, but when in the city, you just have print statements. They have to move around the markets, restaurants, banks.
2. Reduced functionality. That means things like only one restaurant integrated, only buses (no car), homes but not apartments. So, most everything is there, just not all the normative behaviors.

Any others? You can comment; you know what your team is doing.

This is not a substitute for failing to do individual work. It is an attempt to simplify the larger picture that must be solved during integration. For example, if you pick (2) and the reduced functionality is all because of you, you will get a zero.

**Comment by ryeant** [comment]
God, that issue title almost gave me a heart attack.

**Comment by smoran02** [comment]
With the reduced functionality would it still be due on Tuesday?

**Comment by diegovb** [comment]
Is reduced functionality one of those options, or several?

**Comment by choiRyan** [comment]
Reading the reduced functionality definitions: What are the differences
between houses and apartments? I inferred both could have multiple
residents, with exactly one owner of the housing building, I've set both to
sometimes needing maintenance. On the assignment page it says the two can
have different configurations. I figured this was just a graphics issue.

**Comment by alghanmi** [comment]
I just want to add a clarification to the second option Professor @dwilczyn discussed:

> like only one restaurant integrated

That one restaurant must be updated not just integrating a standard v2.2 restaurant

**Comment by amymelody** [comment]
Bump. I'd also like to know whether reduced functionality means one option or several.

**Comment by dwilczyn** [comment]
I can tell from that last post that some of you are already calculating what the minimum is that you can turn in. Remember, this whole discussion about reduced functionality is about MINIMUM requirements in order to get a passing or C grade. B is for good work. A is for excellent work.

Some teams are under duress because of team members who dropped and others who are not performing. I have already talked to them about reduced requirements because of their situation. For what they do have to turn in, they will be graded like everyone else.

**Comment by diegovb** [comment]
Well, that should have been specified more clearly.

**Comment by ztanner** [comment]
^ Indeed. It sounded like these "reduced functionalities" wouldn't be viewed upon negatively, but as stated in the original post, would result in a "compliant v1."

**Comment by vikrantsinghal** [comment]
So this is not for people who don't want to kill themselves, but still get a good grade? Why tell us so late?

**Comment by dwilczyn** [comment]
No one has to kill themselves to get a good grade. The project is now 4 weeks old. Many teams are completely done with their v1 and working toward v2. The reduced functionality was offered to teams in danger of submitting nothing. 

Even without the reduced functionality, grading is always the same. C grades for students who do the minimum or average work on assignments or exams. B for students who show more ingenuity and effort, and A for students who do excellent work. 

Compliant work is ALWAYS the minimum for passing grades. This is Viterbi Engineering where top grades are not given for routine work. I hope that isn't how you were brought up.

**Comment by vikrantsinghal** [comment]
The problem is that you specified it kind of LATE. It's also,unfair to compare with those "many" teams, because obviously, they did have time to finish, but we didn't! Not everybody has the same schedule, I think (also, I'm assuming that code doesn't appear out of nowhere, one has to spend time to think and type in). I'm not lying about it.

**Comment by dwilczyn** [comment]
This issue is closed.
