### ISSUE TITLE
Market Clerk

### ISSUE THREAD

**Issue by mgoulis** [usc-csci201-fall2013/simcity201#54]
Hey!

I was wondering if I could tweak the order of operation for my market so that instead of this...

enter the market -> give an order -> wait for its collection -> pay -> leave

which is how it's listed in the assignment, it would work like this...

enter the market -> give an order -> pay -> wait for its collection -> leave

The reason I ask is because it would be easier to handle the non-norm when a customer is short on cash as he can be excused before walking through the scenario and handing over any items. Additionally, there can be an inventory check before the clerk goes to pick up items so a customer can be dismissed if the items aren't in stock.

**Comment by pixelprizm** [comment]
I'm pretty sure you can do it however you want to design it.  That seems like a very minute detail, and it seems like the graders are being very open-ended, so a small detail like that would most likely be fine.
