### ISSUE TITLE
Where is the rubric?

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/simcity201#61]
I thought is was supposed to be posted before the weekend. It sounded like these reduced functionality would be OK for v1 and would not be penalized. Now, that you have clarified reduced functionality will be penalized with a low grade on this assignment, which is half of our overall grade, it would me nice to have some concrete requirements to follow. It is ridiculous that a rubric still isn't posted 3 days before the deadline. We should know how we will be graded, so we can work on the most important functionalities. It is impossible to know what you are expecting from us.

**Comment by ztanner** [comment]
Thank you for saying what I imagine many groups are thinking.

**Comment by choiRyan** [comment]
It has been reiterated that there will not be a public rubric

**Comment by smoran02** [comment]
So if we have only one of our restaurants in the city now we get a C? I was under the impression that was okay for v1.

**Comment by ghost** [comment]
@choiRyan: Incorrect, in #46 it is clearly stated that a Rubric would be posted.

**Comment by austinspiegel** [comment]
@choiRyan It is absolutely absurd that there is not a rubric for this project.  There have been over 60 issues, many of which specify different requirements for this project, and there is still no central document which specifies the requirements and point allocations for V1.  Put yourself in our position!

**Comment by choiRyan** [comment]
I'm not going to have a debate on the absurdity of this situation; I'm working and stressing too.

I find the public rubric interesting conceptually. In lab (W 12-2) @alghanmi stated that grading would have subjective components (i.e. you have a bad market but incorporated A\* the score would be weighted to your strengths such as A*/collision-checking) 
So if this is true how would they define point ranges based on subjective grading principles, short of a list of requirements? It seems variable for every group.

**Comment by chadmart** [comment]
It was my understanding that if you have a city where a person can go into and out of a market, restaurant, bank and home you would get an A for v1. The suicidal thought thread started suggesting otherwise. Can you at least clarify what we should all definitely have?

**Comment by kushaank** [comment]
@chadmart  Yes, we were told the same. If we have a working SimCity ("It looks like SimCity") we would get 75% of the team grade, the rest 25% was our design/design doc

**Comment by smoran02** [comment]
That was my, and I think many others' understanding of v1 as well.

**Comment by chadmart** [comment]
It is hard to judge the grade/quality of our own city when the requirements are so ambiguous and ever changing. I want to make sure I am submitting A work on Tuesday, but how can I be sure of this?

**Comment by crowley1958** [comment]
I am not aware that any company, which hires programmers, posts a RUBRIC. In industry, you either get an A, or you get an F. If you get too many F's, you get fired. The intent of the team project was to bring in some of the real world. The IDEA was that you would learn what it means to have underspecified requirements AND learn to deal with it. Just like you will face in the real world.

Each team should ask if any of their members have worked as interns. Ask them if there was EVER a rubric given to them.

You ALL know what the normative scenarios are. if you get them to work, you get an A. Anything less is not acceptable in the real world of programming.

Quit GRUBBING for a few points. If you have team members that are not performing. TELL US! We will take care of the situation. It either involves the underperformer pulling their weight, or we will make a team of all the underperformers. If you don't tell us about them, we cannot fix the situation. It is probably better to have a team of 3 people you can trust, than a team of 5, with two people you cannot trust.
