### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by theemilyjane** [usc-csci201-fall2013/simcity201#63]
After implementing a lot of the pieces of our city, we started getting an out of memory error. --"Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: GC overhead limit exceeded."
If anyone knows a way to try and fix this please let me know! Thanks!

**Comment by gabelew** [comment]
I've tried increasing heap space through Run->Run Configurations and while it doesn't throw the OutOfMemoryError, it still freezes and animation is extremely laggy.

**Comment by Valakor** [comment]
There have been a couple others with the same problem due to repeated A\* calls. I would look back and find those Issues because I believe they came up with some solutions that actually fixed the problem, instead of simply increasing the heap space allocated to the Java virtual machine.

**Comment by ivandavid14** [comment]
This means you have a pseudo-memory leak. You might be going into an infinite loop and adding objects to a list, but never deleting them from the list or de-referencingv(setting it to null) the list itself (which would invoke the garbage collector). I had a bug like this in my restaurant v2.1 where one of my agent's got into a bad state and the scheduler never returned false and it kept calling a message that added something to a list that ended up having 100s of thousands of tiny objects in it and then it crashed my computer :|.
