### ISSUE TITLE
Not having everyones restaurant integrated

### ISSUE THREAD

**Issue by chadmart** [usc-csci201-fall2013/simcity201#64]
if we only have 1 restaurant with 5 instances for v1 will we get marked down considering we have good animation and a 5 person team?

@dwilczyn said this was okay during office hours, but does that mean we would get a C on the v1 grade?

**Comment by xli438** [comment]
I'm also wondering that if we only have the house not apartment in v1 will it be considered a C grade?

**Comment by choiRyan** [comment]
What are the differences between the two?

**Comment by chadmart** [comment]
duplicate of issue #62
