### ISSUE TITLE
Intersection Traffic Code

### ISSUE THREAD

**Issue by waynchi** [usc-csci201-fall2013/simcity201#67]
Has anyone gotten the Intersection Traffic Code given by Professor Crowley to work?

When we run it directly, the red light stops everything. It doesn't matter if it's at the end of the intersection or not. It just stops.

Has anyone got this to work?

We're not using this, but we feel like it could be of some help still. Thanks!

**Comment by diegovb** [comment]
That is what the demo is supposed to do,  having it do what you are
expecting it to do is our responsibility.

**Comment by waynchi** [comment]
Oh, Ok. I thought wrong then. My bad haha
