### ISSUE TITLE
Importing repository into Eclipse

### ISSUE THREAD

**Issue by khupka** [usc-csci201-fall2013/simcity201#68]
When opening a new project in eclipse to after re-cloning the project, the src package is not expandable.  When we set up the project from the build.xml, the res folder is there but the src package is blank. How do we fix this?
@alghanmi @crowley1958 @dwilczyn

**Comment by crowley1958** [comment]
I believe you need to "import" the project, not create a new one.

**Comment by khupka** [comment]
Figured it out! There was a problem with the .project file.
