### ISSUE TITLE
Dont be An A**Hole On issues

### ISSUE THREAD

**Issue by chrismclaughlin55** [usc-csci201-fall2013/simcity201#70]
If someone makes an issue. don't respond with useless comments. nobody wants to read your nerd rage comments.

for an example of what not to do,  look at @diegovb and @erikstrottmann  on issue #69

**Comment by choiRyan** [comment]
Well me neither.
Close #70 ?

**Comment by eerie444** [comment]
what's a**? please post a tutorial on this advanced new algorithm

**Comment by eerie444** [comment]
Sorry, but I think it's a little extreme to make an entirely new issue about this. I was trying to lighten the mood a bit; I know you're as stressed out as I am. "Dont be an A**Hole On issues" is in hardly more mature than my own sarcastic "buy a faster computer".

**Comment by khupka** [comment]
@alghanmi @dwilczyn @crowley1958 
Please close this issue.
