### ISSUE TITLE
In our case at least, I don't see how it's going to be possible to integrate our individual Restaurant v2.2's

### ISSUE THREAD

**Issue by ghost** [usc-csci201-fall2013/simcity201#81]
Reason 1: 

We have a little bit more advanced base agent class. Yes, it has a little bit of  mechanism. I apologize for this, but it allows our agents to be completely thread safe without having to use (abuse) synchronization tools in derived classes. Because of this, only one person in our group (me) has had to have a firm grasp of thread safety, everyone else just follows my conventions and it just works. Synchronization crisis averted before it began. 

Reason 2:

Our A\* solution. We use a Moveable abstract agent which interacts with a MovementManager agent in a client/server (respectively) fashion. The reason why is well because much more is possible with this than a simple array of semaphores (grid squares can have multiple attributes like whether it can be occupied by certain types of things and what direction something can move from from that square, also supports things that take up more than one square) and also it has pretty much abstracted away A_, so no one except me has to understand A_ for us to have A\* everywhere. The interior of each building has a MovementManager guiding each Moveable within it. Moveable extends Agent. If we tried to cram this functionality into our Restaurant v2.2 code, we would each have to drop our base agent classes that we used in our old restaurants, use our city's base agent, and with the way it works, we would have to rewrite all of our message methods. Message methods: not salvageable. 

Reason 3:

The person that wrote our restaurant for our v1, wrote it from scratch. He did not use any of his Restaurant v2.2 code, and claims it would have been non-integrable and he'd still be trying to integrate it to this day. He claims his design is completely different from v2.2 design because of what is made possible by A\* and certain assumptions we can now make because of how our base agent class works. It has the revolving stand monitor shared data mechanism, but would he even get a the points for his restaurant in his individual grade since he did not actually use any of his v2.2 code? It just seems like integrating all our restaurants would be more work than all the other work we've done combined. 

Reason 4:

Our restaurants were simply not designed to be aware that they are in a city. Say Maxis wanted to the player to be able to have a much more detailed view of each individual person's life (like in The Sims) in their next Sim City game. I highly doubt they would start by trying to directly collide code from The Sims into Sim City. I'm thinking they would just start with changing Sim City in a normal software development process until the requirements are met. Maxis also makes a game called Spore. You can have cities on planets but they aren't nearly as detailed as a city in Sim City. What if they wanted much more detailed cities in Spore? Would they start by trying to slam their Sim City code into their Spore code? I highly doubt it. 

Some of us are thinking about just not trying to integrate our v2.2 code and just take the 10% hit to our individual scores. We have other tasks. I personally probably wont get around to it. I have more important tasks for this project, and I know what a monitor is, our base agent class is a form of monitor in fact. 

I realize that we all have to have some individual work in order to be graded individually, but [Insert something intelligent here].

**Comment by pixelprizm** [comment]
If you don't think you have time to finish all the restaurant integration, maybe you could at least get a little partial credit for your personal scores by putting the restaurants in but not fully integrated.  For example, Persons go into the restaurant and become RestaurantCustomers, but the Host and Waiters and Cook and Cashier always remain in the restaurant, Agents instead of roles that the PersonAgent can occupy.  Then you would only have to change CustomerRole a little.  That wouldn't take nearly as much time as trying to get the job switching to work.

**Comment by ghost** [comment]
_It just seems like integrating all our restaurants would be more work than all the other work we've done combined._

_Our restaurants were simply not designed to be aware that they are in a city._

There is definitely a lot of truth in these statements.  Integration of restaurants has proved very challenging, but it is possible.  We opted to run the GUIs in the city and the restaurants completely separately.  Collisions in the city are prevented & handled one way; each restaurant uses its own method of doing so (whether this is a strategic layout, A*, or something else, is left to be determined by each team member).

**Comment by ghost** [comment]
@egauderman @sciencepro 

Wait are either of you CP's?

**Comment by ghost** [comment]
@mpdetwiler negative

**Comment by diegovb** [comment]
They aren't.

**Comment by pixelprizm** [comment]
@mpdetwiler nope lol just putting out ideas

**Comment by ghost** [comment]
Oh okay no that's cool I appreciate your feedback.

**Comment by dwilczyn** [comment]
"I realize that we all have to have some individual work in order to be graded individually, but [Insert something intelligent here]."

I will try to figure out something intelligent to say here later in the early afternoon. Given what you have done, some accommodation should be straightforward to work out.
