### ISSUE TITLE
Eclipse doesn't run all of the unit tests

### ISSUE THREAD

**Issue by dacaraway** [usc-csci201-fall2013/simcity201#82]
When I run my unit test on my person, only one of the tests runs (not even the first one).  All of the tests start with the word test and running all of the tests is selected in my setting.  The test doesn't turn green but it doesn't turn red it just says Runs : 1/3

Does anyone know what might be happening?

**Comment by kunalvsh** [comment]
this happened to me before, and the problem was that the semaphore wasn't being released--not sure if that's your problem though

**Comment by dacaraway** [comment]
oh. duh. 
thanks Kunal you da man!!!!
