### ISSUE TITLE
Presentation Content

### ISSUE THREAD

**Issue by paigekehoe** [usc-csci201-fall2013/simcity201#90]
My group and I were just curious what all we are supposed to cover in our presentations.  
Are we just supposed to go through the requirements and talk about how we met them?  Are we going to be running our projects in front of people - or use pictures to show how it works or videos?

We just want to be prepared to cover everything we need to!

@dwilczyn @crowley1958 @alghanmi

**Comment by dwilczyn** [comment]
You will be doing your demos in front of two CP's. They will direct you to run a variety of the scenarios in the rubric. The professors will be close by for ... stuff that arises. You will meet with the professors after your 90 minutes to discuss the grade you got from the CPs.
