### ISSUE TITLE
Do all scenarios require all workplaces and people working?

### ISSUE THREAD

**Issue by clay-to-n** [usc-csci201-fall2013/simcity201#91]
For Scenario C, it requires the market and the restaurant.  For loading this scenario, is it acceptable to include only these buildings, and perhaps houses for the people who work there?  Or do we need markets and banks fully functioning, even thought they are not part of the required scenario?  My team would prefer the former, as it would be easier to tell that the scenario itself works without the clutter of unrelated things happening. 

For Scenario A, it says "Day starts and all workers go to work. One not-working person eats at home..." Does this imply that in Scenario A, workers can immediately go to work and stay there for the duration of the scenario, and don't have to have a house or do normal things such as eat and sleep? This would make it easier because then we could just watch that person and see that they visit every building correctly, without other people leaving work and doing other events.

@alghanmi @dwilczyn @crowley1958

**Comment by clay-to-n** [comment]
Accidentally posted the issue without body text - I edited the body in - sorry e-mail watchers!

**Comment by Valakor** [comment]
Bump. Our current program has a scenario selection pane that lets you run specific scenarios; however, we only create the buildings and people pertinent to the scenario. I.E.: For the market-restaurant delivery, only a single restaurant and market are created, and only a skeleton crew at each is created without homes to return to. This was for the express purpose of making it extremely easy to see that a scenario worked without introducing outside variables.

We do plan to have a fully functioning city with all the buildings and people required for all scenarios to be possible at once, but for testing individual scenarios it seems our approach is much easier.

**Comment by crowley1958** [comment]
Prof Wilczynski should also chime in, but having just what you need in the smaller scenarios makes sense to me.

@dwilczyn

**Comment by dwilczyn** [comment]
To me as well.

**Comment by clay-to-n** [comment]
Great, thanks.
