### ISSUE TITLE
I SURVIVED

### ISSUE THREAD

**Issue by FluffySheep** [usc-csci201-fall2013/simcity201#93]
![comic-simcity-6](https://f.cloud.github.com/assets/2661665/1722239/01a1f182-623d-11e3-93de-4fb95f82d44d.png)

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

![comic-simcity-6-2](https://f.cloud.github.com/assets/2661665/1722240/0341a258-623d-11e3-8849-975a34eb00b2.png)

**Comment by Valakor** [comment]
<3 @usc-csci201-fall2013/students

**Comment by ztanner** [comment]
Pretty sure the latter image needs to be made into a t-shirt.

**Comment by lee533** [comment]
yeaaaaaaah.

**Comment by diegovb** [comment]
omg this is great hahaha

**Comment by diegovb** [comment]
I actually did all of those but the restroom and the sleeping hahaha

**Comment by Yunying** [comment]
Wanna cry 55555555555555

**Comment by Seioch** [comment]
Yay!!!!!!!!!!!!!!!!!!!!!!!!!!!!! I'm gonna crash now!!!!!!!!!!!!!!!! Good night X_x

**Comment by nchootong** [comment]
I suspect there will be a large intoxication gathering for all those who survived this course. <3

**Comment by FluffySheep** [comment]
when and where

**Comment by erikajoh** [comment]
SAL

**Comment by amymelody** [comment]
No Brian this is all a dream. You never finished SimCity201. In fact this IS SimCity201 and we are all residents.

**Comment by diegovb** [comment]
But my bed is so comfy right now tho

**Comment by ztanner** [comment]
@jmdigiov http://inception.davepedu.com/

**Comment by nchootong** [comment]
It's nice to finally take A\* breather and wait for presentations to role around.

**Comment by dhata** [comment]
dreaming about SimCity is a real thing.
